apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources: # specify multiple different configurations, for example:
  - deployment.yaml
  - image-repository.yaml
  - service.yaml
  - rbac.yaml
  images:
  - name: SERVICE APP IMAGE NAME
    newTag: 
