apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources: # specify multiple different configurations, for example:
  - cronjob.yaml
  - image-policy.yaml
  - image-repository.yaml
  - kustomization.yaml
  - rbac.yaml
  images:
  - name: TRAINING APP IMAGE NAME
    newTag: 
